language: perl

perl:
  - "5.30"
os:
  - linux
  
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
    
install:
  - cpanm -v --installdeps --notest .
  # Force latest version of these modules
  - cpanm Scalar::Util
  - cpanm Compress::LZO  
  - cpanm Compress::Raw::Zlib
  - cpanm Compress::Raw::Bzip2
  - cpanm IO::Compress::Base
